Add validator for invalid/empty url
zero-to-mastery/breads-client pull request #68
Opened 2021-03-23 12:39 UTC by shawnk0723

2021-03-24 23:00 UTC, aTmb405 requested changes

2021-03-24 23:00 UTC, aTmb405 commented on src/common/ArticleForm.tsx
> +            errors: ''
See other comment - errors are handled in the redux store.

2021-03-25 08:58 UTC, shawnk0723 commented
Refactored validator for invalid/empty url to use addAlert() action to dispatch an error alert message. Attached the screenshots as well. Please let me know if there's any other issues with this update. 

![validator2](https://user-images.githubusercontent.com/40378909/112446556-9216ef80-8d0d-11eb-9068-6dc17bd9f066.png)

![validator1](https://user-images.githubusercontent.com/40378909/112446580-980cd080-8d0d-11eb-8900-83706cae0736.png)

2021-03-25 09:03 UTC, shawnk0723 commented on src/common/ArticleForm.tsx
> +            this.setState({errors: ''})
Hey Austin, fixed the code per your request. Please review and let me know if there's any other issues with it.

2021-03-28 22:26 UTC, aTmb405 approved these changes
Looks great! Thanks for the changes

2021-03-28 22:26 UTC, merged